import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import Link from "next/link";
import { ArrowLeft, ClipboardList, CheckCircle2 } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function NewReceiptPage() {
  const products = await prisma.product.findMany({ orderBy: { name: "asc" } });
  const locations = await prisma.location.findMany({ orderBy: { name: "asc" } });

  // Generate standardized sequential reference WH/IN/0001 per Mockup specification
  const receiptCount = await prisma.stockMove.count({ where: { documentType: "Receipt" } });
  const autoGeneratedRef = `WH/IN/${String(receiptCount + 1).padStart(4, "0")}`;

  // Auto-fill responsible with currently logged in user per Mockup note
  const cookieStore = await cookies();
  const authCookie = cookieStore.get("auth");
  let defaultResponsible = "Alex Morgan (Warehouse Lead)";
  if (authCookie?.value) {
    try {
      const parsed = JSON.parse(authCookie.value);
      if (parsed.name) defaultResponsible = parsed.name;
    } catch {}
  }

  async function createReceipt(formData: FormData) {
    "use server";
    const partner = (formData.get("partner") as string)?.trim() || "Standard Vendor";
    const reference = (formData.get("reference") as string)?.trim() || autoGeneratedRef;
    const productId = formData.get("productId") as string;
    const toLocationId = formData.get("toLocationId") as string;
    const quantity = Math.max(1, parseInt((formData.get("quantity") as string) || "1"));
    const scheduledDateStr = formData.get("scheduledDate") as string;
    const responsible = (formData.get("responsible") as string)?.trim() || defaultResponsible;
    const initialStatus = (formData.get("status") as string) || "Ready";

    if (!productId || !toLocationId) {
      return;
    }

    await prisma.stockMove.create({
      data: {
        reference,
        partner,
        productId,
        toLocationId,
        quantity,
        documentType: "Receipt",
        status: initialStatus,
        responsible,
        scheduledDate: scheduledDateStr ? new Date(scheduledDateStr) : new Date(),
      },
    });

    redirect("/dashboard/receipts");
  }

  return (
    <div className="p-6 lg:p-8 max-w-3xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <Link
            href="/dashboard/receipts"
            className="inline-flex items-center gap-1.5 text-xs text-indigo-600 hover:text-indigo-800 font-medium mb-2"
          >
            <ArrowLeft size={14} /> Back to Receipts
          </Link>
          <h1 className="text-3xl font-bold text-slate-900 flex items-center gap-2.5">
            <ClipboardList className="text-indigo-600" /> New Incoming Receipt
          </h1>
          <p className="text-slate-500 mt-1">Receive items from vendors and increment inventory</p>
        </div>

        {/* Mockup Status Progression Bar */}
        <div className="hidden sm:flex items-center bg-slate-100 rounded-lg p-1 text-xs font-semibold">
          <span className="px-2.5 py-1 rounded bg-white text-indigo-700 shadow-2xs">Draft</span>
          <span className="px-1 text-slate-300">›</span>
          <span className="px-2 py-1 text-slate-400">Waiting</span>
          <span className="px-1 text-slate-300">›</span>
          <span className="px-2 py-1 text-slate-400">Ready</span>
          <span className="px-1 text-slate-300">›</span>
          <span className="px-2 py-1 text-slate-400">Done</span>
        </div>
      </div>

      <form
        action={createReceipt}
        className="bg-white p-6 sm:p-8 rounded-2xl shadow-sm border border-slate-200 space-y-6"
      >
        {/* Top Reference & Vendor Information */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider mb-1.5">
              Receive From (Supplier / Vendor) *
            </label>
            <input
              type="text"
              name="partner"
              required
              placeholder="e.g. Apex Industrial Supplies Ltd"
              className="w-full px-4 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
            />
          </div>

          <div>
            <div className="flex justify-between items-center mb-1.5">
              <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider">
                Reference Code (WH/IN/xxxx)
              </label>
              <span className="text-[10px] text-indigo-600 font-semibold">Auto Generated</span>
            </div>
            <input
              type="text"
              name="reference"
              defaultValue={autoGeneratedRef}
              className="w-full px-4 py-2.5 bg-slate-100 border border-slate-300 rounded-lg text-sm font-mono font-semibold text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
            />
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider mb-1.5">
              Scheduled Date
            </label>
            <input
              type="date"
              name="scheduledDate"
              defaultValue={new Date().toISOString().split("T")[0]}
              className="w-full px-4 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
            />
          </div>

          <div>
            <div className="flex justify-between items-center mb-1.5">
              <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider">
                Responsible Staff
              </label>
              <span className="text-[10px] text-slate-400">Logged-in User</span>
            </div>
            <input
              type="text"
              name="responsible"
              defaultValue={defaultResponsible}
              className="w-full px-4 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
            />
          </div>
        </div>

        {/* Product Lines Section */}
        <div className="pt-4 border-t border-slate-100 space-y-4">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600">
            Products To Receive
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Select Product *
              </label>
              <select
                name="productId"
                required
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
              >
                <option value="">Select product...</option>
                {products.map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.name} ({p.sku})
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Destination Location / Warehouse *
              </label>
              <select
                name="toLocationId"
                required
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
              >
                <option value="">Select destination...</option>
                {locations.map((l) => (
                  <option key={l.id} value={l.id}>
                    {l.name} {l.isWarehouse ? "(Warehouse)" : ""}
                  </option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Quantity Received *
              </label>
              <input
                type="number"
                name="quantity"
                required
                min="1"
                defaultValue={50}
                className="w-full px-4 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition font-semibold"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Initial State
              </label>
              <select
                name="status"
                className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
              >
                <option value="Ready">Ready (Immediate Validation)</option>
                <option value="Waiting">Waiting (Truck in transit)</option>
                <option value="Draft">Draft (Preliminary PO)</option>
              </select>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="pt-4 flex items-center justify-between border-t border-slate-100">
          <Link
            href="/dashboard/receipts"
            className="px-5 py-2.5 text-slate-600 hover:bg-slate-100 rounded-lg text-sm font-medium transition"
          >
            Cancel
          </Link>
          <button
            type="submit"
            className="bg-indigo-600 text-white px-6 py-2.5 rounded-lg text-sm font-semibold hover:bg-indigo-700 active:scale-[0.98] transition shadow-md shadow-indigo-200 flex items-center gap-2"
          >
            <CheckCircle2 size={16} /> Save Receipt
          </button>
        </div>
      </form>
    </div>
  );
}
