"use client";

import { useState } from "react";
import Link from "next/link";
import { Truck, AlertTriangle, CheckCircle2 } from "lucide-react";

interface ProductItem {
  id: string;
  name: string;
  sku: string;
  uom: string;
  stockQuants: {
    quantity: number;
    locationId: string;
  }[];
}

interface LocationItem {
  id: string;
  name: string;
  isWarehouse: boolean;
}

export default function DeliveryOrderForm({
  products,
  locations,
  autoGeneratedRef,
  defaultResponsible,
  createDeliveryAction,
}: {
  products: ProductItem[];
  locations: LocationItem[];
  autoGeneratedRef: string;
  defaultResponsible: string;
  createDeliveryAction: (formData: FormData) => Promise<void>;
}) {
  const [selectedProductId, setSelectedProductId] = useState<string>(products[0]?.id || "");
  const [selectedLocationId, setSelectedLocationId] = useState<string>(locations[0]?.id || "");
  const [quantity, setQuantity] = useState<number>(10);

  const selectedProduct = products.find((p) => p.id === selectedProductId);
  const matchingQuant = selectedProduct?.stockQuants.find(
    (q) => q.locationId === selectedLocationId
  );
  const availableStock = matchingQuant ? matchingQuant.quantity : 0;
  const totalStockAcrossAll =
    selectedProduct?.stockQuants.reduce((s, q) => s + q.quantity, 0) || 0;

  const isOutOfStock = availableStock <= 0;
  const isExceedingStock = quantity > availableStock && availableStock > 0;

  return (
    <form
      action={createDeliveryAction}
      className="bg-white p-6 sm:p-8 rounded-2xl shadow-sm border border-slate-200 space-y-6"
    >
      {/* Out of Stock Alert Banner - Exactly as noted in Excalidraw mockup */}
      {(isOutOfStock || isExceedingStock) && (
        <div className="p-4 bg-amber-50 border border-amber-300 rounded-xl flex items-start gap-3 text-amber-900 animate-in fade-in duration-200">
          <AlertTriangle className="text-amber-600 shrink-0 mt-0.5" size={20} />
          <div className="text-xs space-y-1">
            <p className="font-bold text-sm text-amber-950">
              {isOutOfStock ? "🚨 Warning: Product is Out of Stock!" : "⚠ Warning: Requested Quantity Exceeds Available Stock!"}
            </p>
            <p>
              Available at selected location: <strong>{availableStock} {selectedProduct?.uom}</strong> (System total across all locations: {totalStockAcrossAll} {selectedProduct?.uom}).
            </p>
            <p className="text-amber-800">
              You can still create the delivery in <strong>Waiting</strong> state, but it cannot be validated until replenished or transferred.
            </p>
          </div>
        </div>
      )}

      {/* Reference & Customer */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider mb-1.5">
            Delivery Address / Customer *
          </label>
          <input
            type="text"
            name="partner"
            required
            placeholder="e.g. Zenith Global Logistics & Retail"
            className="w-full px-4 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
          />
        </div>

        <div>
          <div className="flex justify-between items-center mb-1.5">
            <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider">
              Reference Code (WH/OUT/xxxx)
            </label>
            <span className="text-[10px] text-indigo-600 font-semibold">Auto Generated</span>
          </div>
          <input
            type="text"
            name="reference"
            defaultValue={autoGeneratedRef}
            className="w-full px-4 py-2.5 bg-slate-100 border border-slate-300 rounded-lg text-sm font-mono font-semibold text-slate-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
          />
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div>
          <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider mb-1.5">
            Scheduled Date
          </label>
          <input
            type="date"
            name="scheduledDate"
            defaultValue={new Date().toISOString().split("T")[0]}
            className="w-full px-4 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
          />
        </div>

        <div>
          <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider mb-1.5">
            Operation Type
          </label>
          <input
            type="text"
            name="operationType"
            defaultValue="Outgoing Customer Delivery"
            readOnly
            className="w-full px-4 py-2.5 bg-slate-100 border border-slate-200 rounded-lg text-sm text-slate-600"
          />
        </div>

        <div>
          <div className="flex justify-between items-center mb-1.5">
            <label className="block text-xs font-bold text-slate-600 uppercase tracking-wider">
              Responsible
            </label>
            <span className="text-[10px] text-slate-400">Logged-in</span>
          </div>
          <input
            type="text"
            name="responsible"
            defaultValue={defaultResponsible}
            className="w-full px-4 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
          />
        </div>
      </div>

      {/* Products Table Section */}
      <div className="pt-4 border-t border-slate-100 space-y-4">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600">
          Products To Dispatch
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Select Product *
            </label>
            <select
              name="productId"
              required
              value={selectedProductId}
              onChange={(e) => setSelectedProductId(e.target.value)}
              className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
            >
              <option value="">Select product...</option>
              {products.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name} ({p.sku})
                </option>
              ))}
            </select>
          </div>

          <div>
            <div className="flex justify-between items-center mb-1">
              <label className="block text-xs font-semibold text-slate-700">
                Source Location / Warehouse *
              </label>
              <span className="text-[11px] text-indigo-700 font-bold">
                Available: {availableStock} {selectedProduct?.uom}
              </span>
            </div>
            <select
              name="fromLocationId"
              required
              value={selectedLocationId}
              onChange={(e) => setSelectedLocationId(e.target.value)}
              className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
            >
              <option value="">Select source location...</option>
              {locations.map((l) => (
                <option key={l.id} value={l.id}>
                  {l.name} {l.isWarehouse ? "(Warehouse)" : ""}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Quantity to Dispatch *
            </label>
            <input
              type="number"
              name="quantity"
              required
              min="1"
              value={quantity}
              onChange={(e) => setQuantity(Math.max(1, Number(e.target.value)))}
              className={`w-full px-4 py-2.5 bg-white border rounded-lg text-sm font-semibold transition ${
                isOutOfStock || isExceedingStock
                  ? "border-amber-400 focus:ring-amber-500"
                  : "border-slate-300 focus:ring-indigo-500"
              }`}
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Initial Stage
            </label>
            <select
              name="status"
              className="w-full px-3.5 py-2.5 bg-slate-50 border border-slate-300 rounded-lg text-sm focus:bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500 transition"
            >
              <option value="Waiting">Waiting (Pending Picking & Packing)</option>
              <option value="Draft">Draft</option>
              <option value="Ready">Ready for Immediate Shipping</option>
            </select>
          </div>
        </div>
      </div>

      <div className="pt-4 flex items-center justify-between border-t border-slate-100">
        <Link
          href="/dashboard/deliveries"
          className="px-5 py-2.5 text-slate-600 hover:bg-slate-100 rounded-lg text-sm font-medium transition"
        >
          Cancel
        </Link>
        <button
          type="submit"
          className="bg-indigo-600 text-white px-6 py-2.5 rounded-lg text-sm font-semibold hover:bg-indigo-700 active:scale-[0.98] transition shadow-md shadow-indigo-200 flex items-center gap-2"
        >
          <CheckCircle2 size={16} /> Create Delivery Order
        </button>
      </div>
    </form>
  );
}
