import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import { cookies } from "next/headers";
import Link from "next/link";
import { ArrowLeft, Truck } from "lucide-react";
import DeliveryOrderForm from "./DeliveryOrderForm";

export const dynamic = "force-dynamic";

export default async function NewDeliveryPage() {
  const products = await prisma.product.findMany({
    include: {
      stockQuants: {
        select: { quantity: true, locationId: true },
      },
    },
    orderBy: { name: "asc" },
  });

  const locations = await prisma.location.findMany({ orderBy: { name: "asc" } });

  // Generate standardized sequential reference WH/OUT/0001 per Mockup specification
  const deliveryCount = await prisma.stockMove.count({ where: { documentType: "Delivery" } });
  const autoGeneratedRef = `WH/OUT/${String(deliveryCount + 1).padStart(4, "0")}`;

  // Auto-fill responsible with currently logged in user per Mockup note
  const cookieStore = await cookies();
  const authCookie = cookieStore.get("auth");
  let defaultResponsible = "Alex Morgan (Fulfillment)";
  if (authCookie?.value) {
    try {
      const parsed = JSON.parse(authCookie.value);
      if (parsed.name) defaultResponsible = parsed.name;
    } catch {}
  }

  async function createDelivery(formData: FormData) {
    "use server";
    const partner = (formData.get("partner") as string)?.trim() || "Customer Order";
    const reference = (formData.get("reference") as string)?.trim() || autoGeneratedRef;
    const productId = formData.get("productId") as string;
    const fromLocationId = formData.get("fromLocationId") as string;
    const quantity = Math.max(1, parseInt((formData.get("quantity") as string) || "1"));
    const scheduledDateStr = formData.get("scheduledDate") as string;
    const responsible = (formData.get("responsible") as string)?.trim() || defaultResponsible;
    const initialStatus = (formData.get("status") as string) || "Waiting";

    if (!productId || !fromLocationId) {
      return;
    }

    await prisma.stockMove.create({
      data: {
        reference,
        partner,
        productId,
        fromLocationId,
        quantity,
        documentType: "Delivery",
        status: initialStatus,
        responsible,
        scheduledDate: scheduledDateStr ? new Date(scheduledDateStr) : new Date(),
      },
    });

    redirect("/dashboard/deliveries");
  }

  return (
    <div className="p-6 lg:p-8 max-w-3xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <Link
            href="/dashboard/deliveries"
            className="inline-flex items-center gap-1.5 text-xs text-indigo-600 hover:text-indigo-800 font-medium mb-2"
          >
            <ArrowLeft size={14} /> Back to Delivery Orders
          </Link>
          <h1 className="text-3xl font-bold text-slate-900 flex items-center gap-2.5">
            <Truck className="text-indigo-600" /> New Delivery Order
          </h1>
          <p className="text-slate-500 mt-1">Dispatch goods to a customer with pick & pack tracking</p>
        </div>

        {/* Mockup Status Progression Bar */}
        <div className="hidden sm:flex items-center bg-slate-100 rounded-lg p-1 text-xs font-semibold">
          <span className="px-2.5 py-1 rounded bg-white text-indigo-700 shadow-2xs">Draft</span>
          <span className="px-1 text-slate-300">›</span>
          <span className="px-2 py-1 text-slate-400">Waiting</span>
          <span className="px-1 text-slate-300">›</span>
          <span className="px-2 py-1 text-slate-400">Ready</span>
          <span className="px-1 text-slate-300">›</span>
          <span className="px-2 py-1 text-slate-400">Done</span>
        </div>
      </div>

      <DeliveryOrderForm
        products={products}
        locations={locations}
        autoGeneratedRef={autoGeneratedRef}
        defaultResponsible={defaultResponsible}
        createDeliveryAction={createDelivery}
      />
    </div>
  );
}
