"use client";

import { Printer } from "lucide-react";

export default function PrintSlipButton({
  title,
  reference,
  date,
  partner,
  productName,
  sku,
  quantity,
  uom,
  locationName,
  responsible,
  type,
}: {
  title: string;
  reference: string;
  date: string;
  partner?: string;
  productName: string;
  sku: string;
  quantity: number;
  uom: string;
  locationName?: string;
  responsible?: string;
  type: "Receipt" | "Delivery";
}) {
  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} - ${reference}</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #1e293b; }
            .header { border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 24px; display: flex; justify-content: space-between; }
            .logo { font-size: 24px; font-weight: 800; color: #4f46e5; }
            .badge { display: inline-block; padding: 4px 12px; background: #e0e7ff; color: #4338ca; border-radius: 9999px; font-size: 12px; font-weight: 600; }
            .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 30px; font-size: 14px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { text-align: left; background: #f8fafc; padding: 12px; font-size: 12px; text-transform: uppercase; color: #64748b; border-bottom: 1px solid #e2e8f0; }
            td { padding: 14px 12px; border-bottom: 1px solid #f1f5f9; font-size: 14px; }
            .footer { margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 12px; color: #94a3b8; display: flex; justify-content: space-between; }
            .signature { margin-top: 40px; border-top: 1px dashed #cbd5e1; width: 200px; text-align: center; padding-top: 8px; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <div class="logo">StockSense IMS</div>
              <p style="margin: 4px 0 0; color: #64748b; font-size: 13px;">Official Warehouse Operation Slip</p>
            </div>
            <div>
              <span class="badge">${type.toUpperCase()} SLIP</span>
              <p style="margin: 6px 0 0; font-size: 12px; text-align: right; color: #64748b;">Ref: ${reference}</p>
            </div>
          </div>

          <div class="meta">
            <div>
              <strong>${type === "Receipt" ? "Vendor / Supplier:" : "Customer / Client:"}</strong> ${partner || "Standard Partner"}<br/>
              <strong>Date:</strong> ${date}<br/>
              <strong>Responsible:</strong> ${responsible || "Warehouse Staff"}
            </div>
            <div>
              <strong>${type === "Receipt" ? "Destination Location:" : "Source Location:"}</strong> ${locationName || "Main Warehouse"}<br/>
              <strong>Operation Status:</strong> Authorized & Verified
            </div>
          </div>

          <table>
            <thead>
              <tr>
                <th>Item Description</th>
                <th>SKU</th>
                <th style="text-align: right;">Quantity</th>
                <th style="text-align: right;">UoM</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>${productName}</strong></td>
                <td>${sku}</td>
                <td style="text-align: right; font-weight: bold;">${quantity}</td>
                <td style="text-align: right;">${uom}</td>
              </tr>
            </tbody>
          </table>

          <div style="display: flex; justify-content: space-between; margin-top: 60px;">
            <div class="signature">Warehouse Officer Signature</div>
            <div class="signature">Carrier / Receiver Signature</div>
          </div>

          <div class="footer">
            <span>Generated by StockSense IMS</span>
            <span>Page 1 of 1</span>
          </div>

          <script>
            window.onload = function() { window.print(); }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <button
      type="button"
      onClick={handlePrint}
      title="Print official operation slip"
      className="inline-flex items-center gap-1 text-xs font-semibold px-2.5 py-1.5 rounded-lg bg-slate-100 text-slate-700 hover:bg-slate-200 transition"
    >
      <Printer size={13} /> Print
    </button>
  );
}
